module.exports = [
  {
    id: 1,
    name: "Half-Coffee",
    // isChecked: false,
    // itemCount: 1,
    // imgUrl: "images/coffe.png",
    // color: AppColors.colorHalfCoffee,
    // isHelp: false,
  },
  {
    id: 2,
    name: "Full-Coffee",
    // isChecked: false,
    // itemCount: 1,
    // imgUrl: "images/coffe.png",
    // color: AppColors.colorFullCoffee,
    // isHelp: false,
  },
  {
    id: 3,
    name: "Raw Tea",
    // isChecked: false,
    // itemCount: 1,
    // imgUrl: "images/teacup.png",
    // color: AppColors.colorTea,
    // isHelp: false,
  },
  {
    id: 4,
    name: "Milk Tea",
    // isChecked: false,
    // itemCount: 1,
    // color: AppColors.colorMilkTea,
    // imgUrl: "images/milktea.png",
    // isHelp: false,
  },
  {
    id: 5,
    name: "Water",
    // isChecked: false,
    // itemCount: 1,
    // color: AppColors.colorWater,
    // imgUrl: "images/water.png",
    // isHelp: false,
  },
  {
    id: 6,
    name: "Help",
    // isChecked: false,
    // itemCount: 1,
    // color: AppColors.colorHelp,
    // imgUrl: "images/help.png",
    // isHelp: true,
  },
];
